# 基础配置
type=xboard
server_type=v2ray
node_id=n
soga_key=

# webapi 或 db 对接任选一个
api=webapi

# webapi 对接信息
webapi_url=
webapi_key=

# db 对接信息
db_host=
db_port=
db_name=
db_user=
db_password=

# 日志文件夹，建议不要修改
log_file_dir=/etc/soga/vmess/

# 用户 ip 缓存文件夹，建议不要修改
ip_user_cache_save_dir=/etc/soga/vmess/

# 更多配置项请看文档根据需求自行添加
